"""Renders the output MCP tools module and server scaffold from ToolDef objects."""
from __future__ import annotations

import textwrap
from datetime import datetime, timezone
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from cli2mcp.config import Config

from cli2mcp.models import ParamDef, ToolDef

try:
    from cli2mcp import __version__
except ImportError:
    __version__ = "0.1.0"

_MODULE_HEADER = '''\
"""MCP tools generated by cli2mcp v{version}
Source: {source_dirs}
Generated: {timestamp}

DO NOT EDIT — this file is auto-generated.
Regenerate with: cli2mcp generate
Add custom tools to mcp_server.py instead.
"""
from __future__ import annotations

import subprocess
from typing import Any
'''

_SERVER_SCAFFOLD = '''\
"""MCP server for {server_name}.

This file was generated once by cli2mcp and will NOT be overwritten on subsequent runs.
Add your own @mcp.tool() functions below the _register_tools(mcp) call.

To regenerate CLI tools, run: cli2mcp generate
"""
from __future__ import annotations

from mcp.server.fastmcp import FastMCP

from {module_stem} import _register_tools

mcp = FastMCP("{server_name}")

# Register auto-generated CLI tools
_register_tools(mcp)

# Add your custom tools below:
# @mcp.tool()
# def my_custom_tool(arg: str) -> str:
#     """My custom tool description."""
#     ...

if __name__ == "__main__":
    mcp.run()
'''


def _format_param_sig(params: list[ParamDef], has_context: bool = False) -> str:
    """Format function signature parameters, skipping hidden and context params."""
    visible = [p for p in params if not p.hidden]
    # 1b: if function uses @click.pass_context, skip the first argument
    # (the ctx param is added by Click and must not appear in the MCP signature)
    if has_context and visible:
        visible = visible[1:]

    # 3d: stdin param handled separately — skip it from the normal param list
    parts: list[str] = []
    required = [p for p in visible if p.required]
    optional = [p for p in visible if not p.required]
    for p in required + optional:
        if p.required:
            parts.append(f"{p.name}: {p.type_annotation}")
        else:
            default = p.default
            if isinstance(default, str):
                default_repr = repr(default)
            elif default is None:
                default_repr = "None"
            else:
                default_repr = repr(default)
            parts.append(f"{p.name}: {p.type_annotation} = {default_repr}")
    return ", ".join(parts)


def _format_param_docs(params: list[ParamDef], has_context: bool = False) -> str:
    """Format NumPy-style parameter documentation block."""
    visible = [p for p in params if not p.hidden]
    if has_context and visible:
        visible = visible[1:]
    if not visible:
        return ""
    lines = ["    Parameters", "    ----------"]
    for p in visible:
        lines.append(f"    {p.name} : {p.type_annotation}")
        desc = p.description or f"The {p.name} parameter."
        if p.choices:
            desc = f"{desc} Choices: {', '.join(p.choices)}."
        if p.mutually_exclusive_group:
            desc = f"{desc} (mutually exclusive with others in group '{p.mutually_exclusive_group}')"
        lines.append(f"        {desc}")
    return "\n".join(lines) + "\n"


def _build_direct_import_kwargs(params: list[ParamDef], has_context: bool = False) -> str:
    visible = [p for p in params if not p.hidden]
    if has_context and visible:
        visible = visible[1:]
    return ", ".join(f"{p.name}={p.name}" for p in visible)


def _render_tool(tool: ToolDef, config: "Config") -> str:
    """Render a single @mcp.tool() function (top-level, unindented)."""
    params_sig = _format_param_sig(tool.parameters, tool.has_context)
    # 3d: append stdin parameter if configured
    if tool.stdin_param:
        stdin_sig = f"{tool.stdin_param}: str = ''"
        params_sig = f"{params_sig}, {stdin_sig}" if params_sig else stdin_sig

    param_docs_section = _format_param_docs(tool.parameters, tool.has_context)
    if param_docs_section:
        param_docs_section = "\n" + param_docs_section

    kwargs_str = _build_direct_import_kwargs(tool.parameters, tool.has_context)

    # 3a: use the tool's specific return type if set, otherwise fall back to str
    return_type = tool.return_type if tool.return_type else "str"

    body_lines = [
        "    result = subprocess.run(",
        "        [",
    ]

    # Command parts
    if tool.cli_command:
        body_lines.append(f"            {repr(tool.cli_command)},")

    # 1d: use subcommand_path if available (nested groups), else fall back to cli_subcommand
    if tool.subcommand_path:
        for sub in tool.subcommand_path:
            body_lines.append(f"            {repr(sub)},")
    elif tool.cli_subcommand and tool.cli_subcommand != tool.cli_command:
        body_lines.append(f"            {repr(tool.cli_subcommand)},")

    # 1e: only emit non-hidden params; 1b: skip ctx param (it's not a real CLI param)
    visible_params = [p for p in tool.parameters if not p.hidden]
    if tool.has_context and visible_params:
        visible_params = visible_params[1:]

    positional_params = [p for p in visible_params if not any(f.startswith("-") for f in p.cli_flags)]
    option_params = [p for p in visible_params if any(f.startswith("-") for f in p.cli_flags)]

    for p in positional_params:
        if p.is_multiple:
            body_lines.append(f"            *(str(v) for v in {p.name}),")
        else:
            body_lines.append(f"            str({p.name}),")

    for p in option_params:
        long_flags = [f for f in p.cli_flags if f.startswith("--")]
        flag = long_flags[0] if long_flags else p.cli_flags[0]
        if p.is_flag:
            body_lines.append(f"            *([{repr(flag)}] if {p.name} else []),")
        elif p.is_multiple:
            body_lines.append(f"            *(f for v in {p.name} for f in [{repr(flag)}, str(v)]),")
        else:
            body_lines.append(f"            {repr(flag)}, str({p.name}),")

    # 3c: per-tool timeout overrides global; fall back to config global
    effective_timeout = tool.timeout if tool.timeout is not None else config.subprocess_timeout
    timeout_line = f"        timeout={effective_timeout}," if effective_timeout is not None else ""

    body_lines += [
        "        ],",
        "        capture_output=True,",
        "        text=True,",
        "        check=False,",
    ]
    if timeout_line:
        body_lines.append(timeout_line)

    # 3d: pipe stdin if configured
    if tool.stdin_param:
        body_lines.append(f"        input={tool.stdin_param},")

    body_lines.append("    )")

    # 3b: improved error message includes both stdout and stderr
    body_lines += [
        "    if result.returncode != 0:",
        r'        raise RuntimeError(',
        r'            f"CLI command failed (exit {result.returncode}):\n"',
        r'            f"stdout: {result.stdout}\nstderr: {result.stderr}"',
        r'        )',
    ]

    # 3b: capture_stderr — include non-empty stderr in successful output
    if config.capture_stderr:
        body_lines += [
            "    _stderr = result.stderr.strip()",
            '    return result.stdout + (f"\\n--- stderr ---\\n{_stderr}" if _stderr else "")',
        ]
    else:
        body_lines.append("    return result.stdout")

    body_lines += [
        "",
        f"    # Direct import alternative (uncomment if {tool.source_function} returns a value):",
        f"    # from {tool.source_module} import {tool.source_function}",
    ]
    if kwargs_str:
        body_lines.append(f"    # return {tool.source_function}({kwargs_str})")
    else:
        body_lines.append(f"    # return {tool.source_function}()")

    body = "\n".join(body_lines)

    summary = tool.description or f"Run {tool.name}"
    return_desc = tool.return_description or "Command output"

    # 3a: if prefer_direct_import, use the richer return type in the signature
    sig_return = return_type if config.prefer_direct_import else "str"

    return (
        f"\n\n@mcp.tool()\n"
        f"def {tool.name}({params_sig}) -> {sig_return}:\n"
        f'    """{summary}\n'
        f"{param_docs_section}"
        f"    Returns\n"
        f"    -------\n"
        f"    {sig_return}\n"
        f"        {return_desc}\n"
        f'    """\n'
        f"{body}\n"
    )


def generate_module(tools: list[ToolDef], config: "Config") -> str:
    """Generate the MCP tools module content (always overwritten)."""
    timestamp = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    source_dirs = ", ".join(str(d) for d in config.source_dirs)

    header = _MODULE_HEADER.format(
        version=__version__,
        source_dirs=source_dirs,
        timestamp=timestamp,
    )

    tool_blocks = []
    for tool in tools:
        rendered = _render_tool(tool, config).strip()
        indented = textwrap.indent(rendered, "    ")
        tool_blocks.append("\n\n" + indented)

    body = "".join(tool_blocks)

    register_fn = (
        "\n\ndef _register_tools(mcp) -> None:\n"
        '    """Register all auto-generated CLI tools with the given FastMCP instance."""'
        + body
        + "\n"
    )

    return header + register_fn


def generate_server_scaffold(config: "Config", module_stem: str) -> str:
    """Generate the one-time server scaffold file content."""
    return _SERVER_SCAFFOLD.format(
        server_name=config.server_name,
        module_stem=module_stem,
    )
