"""Renders the output MCP tools module and server scaffold from ToolDef objects."""
from __future__ import annotations

import textwrap
from datetime import datetime, timezone
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from cli2mcp.config import Config

from cli2mcp.models import ParamDef, ToolDef

try:
    from cli2mcp import __version__
except ImportError:
    __version__ = "0.1.0"

_MODULE_HEADER = '''\
"""MCP tools generated by cli2mcp v{version}
Source: {source_dirs}
Generated: {timestamp}

DO NOT EDIT — this file is auto-generated.
Regenerate with: cli2mcp generate
Add custom tools to mcp_server.py instead.
"""
from __future__ import annotations

import subprocess
'''

_SERVER_SCAFFOLD = '''\
"""MCP server for {server_name}.

This file was generated once by cli2mcp and will NOT be overwritten on subsequent runs.
Add your own @mcp.tool() functions below the _register_tools(mcp) call.

To regenerate CLI tools, run: cli2mcp generate
"""
from __future__ import annotations

from mcp.server.fastmcp import FastMCP

from {module_stem} import _register_tools

mcp = FastMCP("{server_name}")

# Register auto-generated CLI tools
_register_tools(mcp)

# Add your custom tools below:
# @mcp.tool()
# def my_custom_tool(arg: str) -> str:
#     """My custom tool description."""
#     ...

if __name__ == "__main__":
    mcp.run()
'''


def _format_param_sig(params: list[ParamDef]) -> str:
    """Format function signature parameters."""
    parts: list[str] = []
    required = [p for p in params if p.required]
    optional = [p for p in params if not p.required]
    for p in required + optional:
        if p.required:
            parts.append(f"{p.name}: {p.type_annotation}")
        else:
            default = p.default
            if isinstance(default, str):
                default_repr = repr(default)
            elif default is None:
                default_repr = "None"
            else:
                default_repr = repr(default)
            parts.append(f"{p.name}: {p.type_annotation} = {default_repr}")
    return ", ".join(parts)


def _format_param_docs(params: list[ParamDef]) -> str:
    """Format NumPy-style parameter documentation block."""
    if not params:
        return ""
    lines = ["    Parameters", "    ----------"]
    for p in params:
        lines.append(f"    {p.name} : {p.type_annotation}")
        desc = p.description or f"The {p.name} parameter."
        if p.choices:
            desc = f"{desc} Choices: {', '.join(p.choices)}."
        lines.append(f"        {desc}")
    return "\n".join(lines) + "\n"


def _build_direct_import_kwargs(params: list[ParamDef]) -> str:
    return ", ".join(f"{p.name}={p.name}" for p in params)


def _render_tool(tool: ToolDef, subprocess_timeout: int | None = None) -> str:
    """Render a single @mcp.tool() function (top-level, unindented)."""
    params_sig = _format_param_sig(tool.parameters)
    param_docs_section = _format_param_docs(tool.parameters)

    if param_docs_section:
        param_docs_section = "\n" + param_docs_section

    kwargs_str = _build_direct_import_kwargs(tool.parameters)

    body_lines = [
        "    result = subprocess.run(",
        "        [",
    ]

    # Command parts
    if tool.cli_command:
        body_lines.append(f"            {repr(tool.cli_command)},")
    if tool.cli_subcommand and tool.cli_subcommand != tool.cli_command:
        body_lines.append(f"            {repr(tool.cli_subcommand)},")

    positional_params = [p for p in tool.parameters if not any(f.startswith("-") for f in p.cli_flags)]
    option_params = [p for p in tool.parameters if any(f.startswith("-") for f in p.cli_flags)]

    for p in positional_params:
        if p.is_multiple:
            body_lines.append(f"            *(str(v) for v in {p.name}),")
        else:
            body_lines.append(f"            str({p.name}),")

    for p in option_params:
        long_flags = [f for f in p.cli_flags if f.startswith("--")]
        flag = long_flags[0] if long_flags else p.cli_flags[0]
        if p.is_flag:
            body_lines.append(f"            *([{repr(flag)}] if {p.name} else []),")
        elif p.is_multiple:
            body_lines.append(f"            *(f for v in {p.name} for f in [{repr(flag)}, str(v)]),")
        else:
            body_lines.append(f"            {repr(flag)}, str({p.name}),")

    timeout_line = f"        timeout={subprocess_timeout}," if subprocess_timeout is not None else ""

    body_lines += [
        "        ],",
        "        capture_output=True,",
        "        text=True,",
        "        check=False,",
    ]
    if timeout_line:
        body_lines.append(timeout_line)
    body_lines += [
        "    )",
        "    if result.returncode != 0:",
        r'        raise RuntimeError(f"CLI command failed:\n{result.stderr}")',
        "    return result.stdout",
        "",
        f"    # Direct import alternative (uncomment if {tool.source_function} returns a value):",
        f"    # from {tool.source_module} import {tool.source_function}",
    ]
    if kwargs_str:
        body_lines.append(f"    # return {tool.source_function}({kwargs_str})")
    else:
        body_lines.append(f"    # return {tool.source_function}()")

    body = "\n".join(body_lines)

    summary = tool.description or f"Run {tool.name}"
    return_desc = tool.return_description or "Command output"

    return (
        f"\n\n@mcp.tool()\n"
        f"def {tool.name}({params_sig}) -> str:\n"
        f'    """{summary}\n'
        f"{param_docs_section}"
        f"    Returns\n"
        f"    -------\n"
        f"    str\n"
        f"        {return_desc}\n"
        f'    """\n'
        f"{body}\n"
    )


def generate_module(tools: list[ToolDef], config: "Config") -> str:
    """Generate the MCP tools module content (always overwritten)."""
    timestamp = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    source_dirs = ", ".join(str(d) for d in config.source_dirs)

    header = _MODULE_HEADER.format(
        version=__version__,
        source_dirs=source_dirs,
        timestamp=timestamp,
    )

    tool_blocks = []
    for tool in tools:
        rendered = _render_tool(tool, config.subprocess_timeout).strip()
        indented = textwrap.indent(rendered, "    ")
        tool_blocks.append("\n\n" + indented)

    body = "".join(tool_blocks)

    register_fn = (
        "\n\ndef _register_tools(mcp) -> None:\n"
        '    """Register all auto-generated CLI tools with the given FastMCP instance."""'
        + body
        + "\n"
    )

    return header + register_fn


def generate_server_scaffold(config: "Config", module_stem: str) -> str:
    """Generate the one-time server scaffold file content."""
    return _SERVER_SCAFFOLD.format(
        server_name=config.server_name,
        module_stem=module_stem,
    )
