"""Renders the output MCP server Python file from ToolDef objects."""
from __future__ import annotations

from datetime import datetime, timezone
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from cli2mcp.config import Config

from cli2mcp.models import ParamDef, ToolDef

try:
    from cli2mcp import __version__
except ImportError:
    __version__ = "0.1.0"

_FILE_HEADER = '''\
"""MCP server generated by cli2mcp v{version}
Source: {source_dirs}
Generated: {timestamp}

Regenerate with: cli2mcp generate
"""
from __future__ import annotations

import subprocess
from mcp.server.fastmcp import FastMCP

mcp = FastMCP("{server_name}")
'''

_TOOL_TEMPLATE = '''

@mcp.tool()
def {tool_name}({params_sig}) -> str:
    """{summary}
{param_docs_section}
    Returns
    -------
    str
        {return_description}
    """
{body}
'''

_MAIN_BLOCK = """
if __name__ == "__main__":
    mcp.run()
"""


def _format_param_sig(params: list[ParamDef]) -> str:
    """Format function signature parameters."""
    parts: list[str] = []
    required = [p for p in params if p.required]
    optional = [p for p in params if not p.required]
    for p in required + optional:
        if p.required:
            parts.append(f"{p.name}: {p.type_annotation}")
        else:
            default = p.default
            if isinstance(default, str):
                default_repr = repr(default)
            elif default is None:
                default_repr = "None"
            else:
                default_repr = repr(default)
            parts.append(f"{p.name}: {p.type_annotation} = {default_repr}")
    return ", ".join(parts)


def _format_param_docs(params: list[ParamDef]) -> str:
    """Format NumPy-style parameter documentation block."""
    if not params:
        return ""
    lines = ["    Parameters", "    ----------"]
    for p in params:
        lines.append(f"    {p.name} : {p.type_annotation}")
        desc = p.description or f"The {p.name} parameter."
        lines.append(f"        {desc}")
    return "\n".join(lines) + "\n"


def _build_cli_args(tool: ToolDef) -> str:
    """Build the list of CLI arguments for subprocess.run as a Python expression string."""
    # Start with command and optional subcommand
    cmd_parts: list[str] = []
    if tool.cli_command:
        cmd_parts.append(repr(tool.cli_command))
    if tool.cli_subcommand and tool.cli_subcommand != tool.cli_command:
        cmd_parts.append(repr(tool.cli_subcommand))

    arg_build_lines: list[str] = []

    # Separate positional from option params
    positional_params = [p for p in tool.parameters if not any(f.startswith("-") for f in p.cli_flags)]
    option_params = [p for p in tool.parameters if any(f.startswith("-") for f in p.cli_flags)]

    for p in positional_params:
        arg_build_lines.append(f"        str({p.name}),")

    for p in option_params:
        long_flags = [f for f in p.cli_flags if f.startswith("--")]
        flag = long_flags[0] if long_flags else p.cli_flags[0]
        if p.is_flag:
            arg_build_lines.append(f"        *([{repr(flag)}] if {p.name} else []),")
        else:
            arg_build_lines.append(f"        {repr(flag)}, str({p.name}),")

    if not cmd_parts and not arg_build_lines:
        return "        []"

    lines = ["        ["]
    for part in cmd_parts:
        lines.append(f"            {part},")
    if arg_build_lines:
        lines.extend(f"        {line}" for line in arg_build_lines)
    lines.append("        ]")
    return "\n".join(lines)


def _build_direct_import_kwargs(params: list[ParamDef]) -> str:
    return ", ".join(f"{p.name}={p.name}" for p in params)


def _render_tool(tool: ToolDef) -> str:
    """Render a single @mcp.tool() function."""
    params_sig = _format_param_sig(tool.parameters)
    param_docs_section = _format_param_docs(tool.parameters)

    if param_docs_section:
        param_docs_section = "\n" + param_docs_section

    cli_args = _build_cli_args(tool)
    kwargs_str = _build_direct_import_kwargs(tool.parameters)

    body_lines = [
        "    result = subprocess.run(",
        "        [",
    ]

    # Command parts
    if tool.cli_command:
        body_lines.append(f"            {repr(tool.cli_command)},")
    if tool.cli_subcommand and tool.cli_subcommand != tool.cli_command:
        body_lines.append(f"            {repr(tool.cli_subcommand)},")

    positional_params = [p for p in tool.parameters if not any(f.startswith("-") for f in p.cli_flags)]
    option_params = [p for p in tool.parameters if any(f.startswith("-") for f in p.cli_flags)]

    for p in positional_params:
        body_lines.append(f"            str({p.name}),")

    for p in option_params:
        long_flags = [f for f in p.cli_flags if f.startswith("--")]
        flag = long_flags[0] if long_flags else p.cli_flags[0]
        if p.is_flag:
            body_lines.append(f"            *([{repr(flag)}] if {p.name} else []),")
        else:
            body_lines.append(f"            {repr(flag)}, str({p.name}),")

    body_lines += [
        "        ],",
        "        capture_output=True,",
        "        text=True,",
        "        check=False,",
        "    )",
        "    if result.returncode != 0:",
        r'        raise RuntimeError(f"CLI command failed:\n{result.stderr}")',
        "    return result.stdout",
        "",
        f"    # Direct import alternative (uncomment if {tool.source_function} returns a value):",
        f"    # from {tool.source_module} import {tool.source_function}",
    ]
    if kwargs_str:
        body_lines.append(f"    # return {tool.source_function}({kwargs_str})")
    else:
        body_lines.append(f"    # return {tool.source_function}()")

    body = "\n".join(body_lines)

    summary = tool.description or f"Run {tool.name}"
    return_desc = tool.return_description or "Command output"

    return (
        f"\n\n@mcp.tool()\n"
        f"def {tool.name}({params_sig}) -> str:\n"
        f'    """{summary}\n'
        f"{param_docs_section}"
        f"    Returns\n"
        f"    -------\n"
        f"    str\n"
        f"        {return_desc}\n"
        f'    """\n'
        f"{body}\n"
    )


def generate_server(tools: list[ToolDef], config: "Config") -> str:
    """Generate the full MCP server Python file content."""
    timestamp = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    source_dirs = ", ".join(str(d) for d in config.source_dirs)

    header = _FILE_HEADER.format(
        version=__version__,
        source_dirs=source_dirs,
        timestamp=timestamp,
        server_name=config.server_name,
    )

    tool_blocks = "".join(_render_tool(tool) for tool in tools)

    return header + tool_blocks + _MAIN_BLOCK
